### PR TITLE
provide motivational message for next actions list

### PR DESCRIPTION
**Pull request by mikemccracken**

### CODE REVIEW

**Comment by tych0** [comment]
+1 LGTM :)

**Comment by hallyn** [comment]
/me looks into whether he can blacklist specific contributors.

**Comment by hallyn** [comment]
```bash
serge@sl:~$ cat gtd/next_actions.otl | ts "please check"

Command 'ts' not found, but can be installed with:

sudo apt install moreutils
```

Please check?

**Comment by mikemccracken** [comment]
replaced with a more standard tool. let's hop on a webex and I can show you how it works

**Comment by hallyn** [comment]
Your webex or mine?

**Pull request closed without merging**
